LOG_DIALOGUE = {
    "label":            "KEEPER'S LOG",
    "reveal_speed":     24.0,
    "font_size":        16,
    "hint_font_size":   9,
    "side_margin":      118,
    "bottom_offset":    124,
    "height":           92,
    "shadow_y":         4,
    "corner_radius":    12,
    "accent_h":         4,
    "fade_time":        0.35,
    "max_alpha":        220,
    "tag_x":            18,
    "tag_y":            10,
    "text_x":           20,
    "text_y":           18,
    "text_y_with_label":28,
    "text_wrap_pad":    44,
    "line_gap":         5,
    "prompt_x":         18,
    "prompt_y":         14,
    "caret_w":          3,
    "caret_trim":       6,
    "caret_x":          6,
    "caret_alpha":      160,
    "caret_speed":      8.0,
    "hint_size":        10,
    "hint_x":           16,
    "hint_y":           5,
    "hint_alpha":       150,
    "hint_speed":       6.0,
    "glow_alpha":       58,
    "text_shadow_alpha":100,
}

THOUGHT_DIALOGUE = {
    "font_size":            12,
    "hint_font_size":       8,
    "padding_x":            14,
    "padding_y":            10,
    "line_gap":             4,
    "safe_margin":          12,
    "tail_gap":             18,
    "max_box_w":            240,
    "extra_bottom":         8,
    "shadow_y":             4,
    "corner_radius":        16,
    "tail_inset":           18,
    "tail_mid_ratio":       0.55,
    "tail_radii":           (8, 5, 3),
    "tail_head_offset":     6,
    "fallback_anchor_x":    12,
    "fallback_anchor_bottom":84,
    "fallback_anchor_w":    24,
    "fallback_anchor_h":    40,
}

OPENING_SCENE = {
    "veil":             (10, 12, 20, 120),
    "pulse_start":      6.0,
    "pulse_end":        10.0,
    "glow_radius":      54,
    "glow_pulse":       16,
    "glow_alpha":       18,
    "glow_alpha_pulse": 40,
    "beacon_radius":    34,
    "beacon_pulse":     6,
    "letterbox_h":      24,
    "letterbox_ratio":  0.06,
    "fade_in":          2.0,
}

LOG_COLORS = {
    "bg":          (14, 14, 24),
    "shadow":      (8, 8, 12),
    "border":      (96, 92, 116),
    "accent":      (172, 152, 108),
    "text":        (230, 225, 210),
    "text_glow":   (132, 126, 156),
    "tag":         (176, 166, 142),
    "prompt":      (150, 146, 164),
}

THOUGHT_COLORS = {
    "bg":     (238, 231, 214),
    "shadow": (52, 42, 46),
    "border": (112, 96, 92),
    "text":   (34, 30, 36),
    "prompt": (102, 94, 96),
}

RED_OVERLAY_ALPHA = {
    1:  0,
    2:  0,
    3:  8,
    4:  10,
    5:  10,
    6:  15,
    7:  20,
    8:  30,
    9:  40,
    10: 60,
}
